### ISSUE TITLE
[Error] Unexpected error: TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by markgajones** [parzival-space/discord-radio-bot#1]
When I run Docker, I get the following error
![image](https://user-images.githubusercontent.com/1552546/182146009-a2d0268b-8d35-428d-821e-67e399176399.png)

**Comment by markgajones** [comment]
It was down to user error

**Comment by sistematico** [comment]
> It was down to user error

Same error here, i'm not sure what i should do.

**Comment by parzival-space** [comment]
> > It was down to user error
> 
> Same error here, i'm not sure what i should do.

Can you send your config.json?

**Comment by sistematico** [comment]
> > > It was down to user error
> > 
> > 
> > Same error here, i'm not sure what i should do.
> 
> Can you send your config.json?

```
{
  "radio": {
    "stream": "https://radio.somdomato.com/principal",
    "volume": 10
  },

  "discord": {
    "token": "TOKEN",
    "channel": "884789840313458698"
  }
}
```

**Comment by parzival-space** [comment]
> > > > It was down to user error
> > > 
> > > 
> > > Same error here, i'm not sure what i should do.
> > 
> > 
> > Can you send your config.json?
> 
> ```
> {
>   "radio": {
>     "stream": "https://radio.somdomato.com/principal",
>     "volume": 10
>   },
> 
>   "discord": {
>     "token": "TOKEN",
>     "channel": "884789840313458698"
>   }
> }
> ```

Okay, my first guess would be, that you forgot to invite the bot to your server or the channel id is wrong.
The line that errors simply prints the name of the server, the bot is on.

You can generate a invite from this site: https://discordapi.com/permissions.html#3146752
The bot needs permissions to 'View Channel', 'Voice Connect' and 'Voice Speak'.

**Comment by sistematico** [comment]
> > > > > It was down to user error
> > > > 
> > > > 
> > > > Same error here, i'm not sure what i should do.
> > > 
> > > 
> > > Can you send your config.json?
> > 
> > 
> > ```
> > {
> >   "radio": {
> >     "stream": "https://radio.somdomato.com/principal",
> >     "volume": 10
> >   },
> > 
> >   "discord": {
> >     "token": "TOKEN",
> >     "channel": "884789840313458698"
> >   }
> > }
> > ```
> 
> Okay, my first guess would be, that you forgot to invite the bot to your server or the channel id is wrong. The line that errors simply prints the name of the server, the bot is on.
> 
> You can generate a invite from this site: https://discordapi.com/permissions.html#3146752 The bot needs permissions to 'View Channel', 'Voice Connect' and 'Voice Speak'.

Thank you very much! All working as expected, except now bot is muted.

**Comment by parzival-space** [comment]
Okay, I identified the problem. Eris, the discord library that I am using, is simply not able to understand the audio data of the radio station.
I am currently switching to a different lib and it looks like that one is working.

**Comment by parzival-space** [comment]
Okay, it turns out that the problem is caused by the radio station transmitting the stream data in 1-second intervals, which is actually quite long considering that the station only transmits 1-second chunks.
I'm currently trying out different buffering techniques. 
This may take some time...

**Comment by parzival-space** [comment]
Also, I created a new issue for this since it clearly no longer belongs in this issue.
See #8
