### ISSUE TITLE
Change URL icecast stream

### ISSUE THREAD

**Issue by allastornin** [parzival-space/discord-radio-bot#9]
Hello. 

Can you tell please, how i can change icecast url, for playing my music?

**Comment by parzival-space** [comment]
Ah sorry. I forgot to document that.

You need to add the following line to your [application.properties](https://github.com/parzival-space/discord-radio-bot#running-the-bot) file:
```properties
stream.url=<<your url>>
```

**Comment by allastornin** [comment]
In what form do you need to indicate url?

stream.url=https://icecast.web.server/stream_name
stream.url=icecast.web.server/stream_name

It didn't work for me

**Comment by parzival-space** [comment]
Can you provide the station url?

I use this station for testing:
Station url: https://play.sas-media.ru/
Stream url: https://play.sas-media.ru/play_256

So the setting should be:
```properties
stream.url=https://play.sas-media.ru/play_256
```

**Comment by allastornin** [comment]
I'm sorry, I forgot to tell you that the prescribed standard station is working.

When I start the application, I receive this message and in the discord from the bot I hear music from this station:
Playing We have chosen for you the best of the world of electronic dance music! by Noise FM - It's Your Lifestyle!

The bot does not play music from any other radio url.

When you specify your icecast server, the bot still continues to broadcast Noise FM.

**Comment by allastornin** [comment]
И судя по зоне url радио станции, я могу перейти на свой язык?))

**Comment by parzival-space** [comment]
Oh shit, I accidentally hard coded the url 😂 
https://github.com/parzival-space/discord-radio-bot/blob/250f79cbff2888c7f4952fd20c5bc921734e8287/src/main/java/space/parzival/discord/radiobot/events/Ready.java#L52

I fix that soon, please give me some time.

**Comment by allastornin** [comment]
It is OK, it happens)

Will wait. Among the many options on the hub, this is the first working one) Just like the old version on the node)

Thank you)

**Comment by allastornin** [comment]
I also noticed that due to - "o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8080" 

There is no way to pick up a second copy of the application. Only if in Docker, with port forwarding to 8081, etc.

**Comment by parzival-space** [comment]
I do not speak Russian, sorry. NoiseFM was just the first radio station I found 😂 

I updated the [hardcoded URL code](https://github.com/parzival-space/discord-radio-bot/blob/4601fb20aae581e835bfbea4b1953fe046629348/src/main/java/space/parzival/discord/radiobot/events/Ready.java#L56).
Also, the integrated web server is now disabled, as it is currently not needed. This should prevent your "Netty started on port 8080" problem.

Please test the latest snapshot build: [0.1.0-SNAPSHOT](https://github.com/parzival-space/discord-radio-bot/releases/tag/0.1.0-SNAPSHOT)
If it works for you, I am planing to release the current build.

**Comment by allastornin** [comment]
Now everything works, thank you very much!

**Comment by allastornin** [comment]
Now everything works, thank you very much!
